#!/usr/bin/env bash
# SPDX-FileCopyrightText: Copyright (C) Nicolas Lamirault <nicolas.lamirault@gmail.com>
# SPDX-License-Identifier: Apache-2.0

set -euo pipefail

# gen-roster.sh — compile team/roster.md from each agent's frontmatter.
#
# The roster is the human-facing "who's who / when do I want this agent" map,
# grouped by tier (orchestrator → executives → specialists). It complements
# team/routing.md, which is Zeus' flat machine-readable matrix: same source of
# truth (agents/*/README.md), different audience. Committed so humans, reviewers,
# and CI browse the same roster. No hermes CLI required.
#
#   gen-roster.sh            # write team/roster.md
#   gen-roster.sh --check    # exit non-zero if team/roster.md is stale

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
AGENTS_DIR="${ROOT}/agents"
OUT="${ROOT}/team/roster.md"

# shellcheck source=hack/lib-frontmatter.sh
. "${ROOT}/hack/lib-frontmatter.sh"

declare -A NAME DOMAIN EMOJI TAGLINE ORDER TIER FIT
shopt -s nullglob
for file in "${AGENTS_DIR}"/*/README.md; do
  n="$(fm_scalar "$file" name)"; [[ -z "$n" ]] && continue
  s="$(echo "$n" | tr '[:upper:]' '[:lower:]')"
  NAME[$s]="$n"
  DOMAIN[$s]="$(fm_scalar "$file" domain)"
  EMOJI[$s]="$(fm_scalar "$file" emoji)"
  TAGLINE[$s]="$(fm_scalar "$file" tagline)"
  ORDER[$s]="$(fm_scalar "$file" order)"
  TIER[$s]="$(fm_scalar "$file" tier)"; TIER[$s]="${TIER[$s]:-specialist}"
  # "Good fit" = the first two `does` items (the agent's headline tasks), with
  # trailing periods stripped and joined by a middot. A middot (not ';') avoids
  # colliding with semicolons that appear inside a does item. Falls back to the
  # tagline when an agent declares no `does` (e.g. a pure orchestrator).
  fit="$(fm_list "$file" does | head -2 | sed 's/[[:space:]]*\.$//' \
    | awk 'NR==1{printf "%s",$0} NR>1{printf " · %s",$0}')"
  FIT[$s]="${fit:-${TAGLINE[$s]}}"
done

# Section title per tier, in presentation order.
tier_rank()  { case "$1" in orchestrator) echo 0 ;; executive) echo 1 ;; *) echo 2 ;; esac; }
tier_title() { case "$1" in orchestrator) echo "Orchestrator" ;; executive) echo "Executives" ;; *) echo "Specialists" ;; esac; }
tier_blurb() {
  case "$1" in
    orchestrator) echo "The single entrypoint. Routes every request; never does specialist work." ;;
    executive)    echo "Own a domain and delegate down to their specialists; cross-domain concerns return to Zeus." ;;
    *)            echo "Each owns one domain and hands off along defined routes, advancing only through PASS/FAIL gates." ;;
  esac
}

# Slugs sorted within a tier by numeric order. Uses `if` (not `&&`) so the loop's
# final iteration exits 0 even when it does not match — otherwise `pipefail`
# propagates the non-matching test's status and `set -e` aborts the caller.
slugs_in_tier() {
  local want="$1" k
  for k in "${!NAME[@]}"; do
    if [[ "${TIER[$k]}" == "$want" ]]; then printf '%s\t%s\n' "${ORDER[$k]:-9999}" "$k"; fi
  done | sort -n -k1,1 | cut -f2
}

render() {
  echo "<!--"
  echo "SPDX-FileCopyrightText: Copyright (C) Nicolas Lamirault <nicolas.lamirault@gmail.com>"
  echo "SPDX-License-Identifier: Apache-2.0"
  echo "-->"
  echo
  echo "<!-- Generated by hack/gen-roster.sh from agents/*/README.md — do not edit by hand. -->"
  echo
  echo "# Agentheon — Roster"
  echo
  echo "Who's who in the pantheon, and when to reach for each agent. Grouped by"
  echo "tier. For Zeus' machine-readable routing matrix (aliases, model, hand-off"
  echo "edges), see [routing.md](routing.md)."
  for tier in orchestrator executive specialist; do
    local_slugs="$(slugs_in_tier "$tier")"
    [[ -n "$local_slugs" ]] || continue
    echo
    echo "## $(tier_title "$tier")"
    echo
    echo "$(tier_blurb "$tier")"
    echo
    echo "| Agent | Domain | Good fit |"
    echo "|-------|--------|----------|"
    while read -r s; do
      [[ -n "$s" ]] || continue
      echo "| ${EMOJI[$s]:+${EMOJI[$s]} }**${NAME[$s]}** | ${DOMAIN[$s]} | ${FIT[$s]} |"
    done <<< "$local_slugs"
  done
}

if [[ "${1:-}" == "--check" ]]; then
  if ! diff -q <(render) "$OUT" >/dev/null 2>&1; then
    echo "🔴 team/roster.md is out of date — run: ./hack/gen-roster.sh" >&2
    diff -u "$OUT" <(render) >&2 || true
    exit 1
  fi
  echo "🟢 team/roster.md is in sync"
  exit 0
fi

render > "$OUT"
echo "🟢 wrote ${OUT}"
