#!/usr/bin/env bash
# SPDX-FileCopyrightText: Copyright (C) Nicolas Lamirault <nicolas.lamirault@gmail.com>
# SPDX-License-Identifier: Apache-2.0

set -euo pipefail

# gen-routing.sh — compile team/routing.md from each agent's frontmatter.
#
# The routing matrix is Zeus' machine-readable map: domain -> agent, with
# aliases, model, reasoning, and hand-off edges. It is generated from the single
# source of truth (agents/*/README.md) and committed so humans, reviewers, and
# CI see the same map the installer feeds to Hermes. No hermes CLI required.
#
#   gen-routing.sh            # write team/routing.md
#   gen-routing.sh --check    # exit non-zero if team/routing.md is stale

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
AGENTS_DIR="${ROOT}/agents"
OUT="${ROOT}/team/routing.md"

# shellcheck source=hack/lib-frontmatter.sh
. "${ROOT}/hack/lib-frontmatter.sh"

declare -A NAME DOMAIN MODEL REASON HANDS ALIASES ORDER TIER
shopt -s nullglob
for file in "${AGENTS_DIR}"/*/README.md; do
  n="$(fm_scalar "$file" name)"; [[ -z "$n" ]] && continue
  s="$(echo "$n" | tr '[:upper:]' '[:lower:]')"
  NAME[$s]="$n"
  DOMAIN[$s]="$(fm_scalar "$file" domain)"
  MODEL[$s]="$(fm_scalar "$file" model)"
  REASON[$s]="$(fm_scalar "$file" reasoning)"
  ORDER[$s]="$(fm_scalar "$file" order)"
  TIER[$s]="$(fm_scalar "$file" tier)"; TIER[$s]="${TIER[$s]:-specialist}"
  HANDS[$s]="$(fm_list "$file" handoffs | paste -sd, - | sed 's/,/, /g')"
  ALIASES[$s]="$(fm_list "$file" aliases | paste -sd, - | sed 's/,/, /g')"
done

# Sort rank for tier: orchestrator first, then executives, then specialists.
tier_rank() { case "$1" in orchestrator) echo 0 ;; executive) echo 1 ;; *) echo 2 ;; esac; }

render() {
  echo "<!--"
  echo "SPDX-FileCopyrightText: Copyright (C) Nicolas Lamirault <nicolas.lamirault@gmail.com>"
  echo "SPDX-License-Identifier: Apache-2.0"
  echo "-->"
  echo
  echo "<!-- Generated by hack/gen-routing.sh from agents/*/README.md — do not edit by hand. -->"
  echo
  echo "# Agentheon — Routing Matrix"
  echo
  echo "Zeus routes to the executive who owns a domain; each executive delegates"
  echo "down to its specialists. Grouped by tier, then role; hand-offs per agent."
  echo
  echo "| Agent | Tier | Aliases | Domain | Model | Reasoning | Hands off to |"
  echo "|-------|------|---------|--------|-------|-----------|--------------|"
  # Sort by tier (orchestrator → executive → specialist), then numeric order.
  for s in $(for k in "${!NAME[@]}"; do printf '%s\t%s\t%s\n' "$(tier_rank "${TIER[$k]}")" "${ORDER[$k]:-9999}" "$k"; done | sort -n -k1,1 -k2,2 | cut -f3); do
    echo "| ${NAME[$s]} | ${TIER[$s]} | ${ALIASES[$s]:-—} | ${DOMAIN[$s]} | ${MODEL[$s]:-?} | ${REASON[$s]:-default} | ${HANDS[$s]:-—} |"
  done
}

if [[ "${1:-}" == "--check" ]]; then
  if ! diff -q <(render) "$OUT" >/dev/null 2>&1; then
    echo "🔴 team/routing.md is out of date — run: ./hack/gen-routing.sh" >&2
    diff -u "$OUT" <(render) >&2 || true
    exit 1
  fi
  echo "🟢 team/routing.md is in sync"
  exit 0
fi

render > "$OUT"
echo "🟢 wrote ${OUT}"
