#!/usr/bin/env bash
# SPDX-FileCopyrightText: Copyright (C) Nicolas Lamirault <nicolas.lamirault@gmail.com>
# SPDX-License-Identifier: Apache-2.0

set -euo pipefail

# gen-crons.sh — compile team/crons.md from each cron's frontmatter.
#
# Scheduled tasks live beside the deity that owns them:
# agents/<slug>/crons/*.md — YAML frontmatter (schedule, skill, delivery
# channel) plus a Markdown body that is the prompt Hermes runs. The owning agent
# is the parent profile directory, so it is derived from the path, never
# duplicated in frontmatter. This matrix is the committed, machine-readable index
# of what runs when, and by whom — the cron analogue of team/routing.md.
# Generated from the single source of truth and committed so humans, reviewers,
# and CI see the same schedule the installer feeds to Hermes. No hermes CLI.
#
#   gen-crons.sh            # write team/crons.md
#   gen-crons.sh --check    # exit non-zero if team/crons.md is stale

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
AGENTS_DIR="${ROOT}/agents"
OUT="${ROOT}/team/crons.md"

# shellcheck source=hack/lib-frontmatter.sh
. "${ROOT}/hack/lib-frontmatter.sh"

declare -A SCHEDULE AGENT SKILL DELIVER SUMMARY
shopt -s nullglob
for file in "${AGENTS_DIR}"/*/crons/*.md; do
  n="$(fm_scalar "$file" name)"; [[ -z "$n" ]] && continue
  SCHEDULE[$n]="$(fm_scalar "$file" schedule)"
  AGENT[$n]="$(basename "$(dirname "$(dirname "$file")")")"
  SKILL[$n]="$(fm_scalar "$file" skill)"
  DELIVER[$n]="$(fm_scalar "$file" deliver)"
  SUMMARY[$n]="$(fm_scalar "$file" summary)"
done

render() {
  echo "<!--"
  echo "SPDX-FileCopyrightText: Copyright (C) Nicolas Lamirault <nicolas.lamirault@gmail.com>"
  echo "SPDX-License-Identifier: Apache-2.0"
  echo "-->"
  echo
  echo "<!-- Generated by hack/gen-crons.sh from agents/*/crons/*.md — do not edit by hand. -->"
  echo
  echo "# Agentheon — Cron Schedule"
  echo
  echo "Scheduled tasks Hermes runs unattended. Each lives beside the deity that"
  echo "owns it and is delivered to one channel. Sorted by name."
  echo
  echo "| Cron | Schedule | Agent | Skill | Deliver | Summary |"
  echo "|------|----------|-------|-------|---------|---------|"
  for n in $(printf '%s\n' "${!SCHEDULE[@]}" | sort); do
    echo "| ${n} | \`${SCHEDULE[$n]}\` | ${AGENT[$n]:-—} | ${SKILL[$n]:-—} | ${DELIVER[$n]:-—} | ${SUMMARY[$n]:-—} |"
  done
}

if [[ "${1:-}" == "--check" ]]; then
  if ! diff -q <(render) "$OUT" >/dev/null 2>&1; then
    echo "🔴 team/crons.md is out of date — run: ./hack/gen-crons.sh" >&2
    diff -u "$OUT" <(render) >&2 || true
    exit 1
  fi
  echo "🟢 team/crons.md is in sync"
  exit 0
fi

render > "$OUT"
echo "🟢 wrote ${OUT}"
